language: ruby
dist: trusty
rvm:
  - 2.2
install: gem install asciidoctor-pdf --pre

git:
  depth: 1
branches:
  only:
  - master
addons:
  apt:
    packages:
    - zsh

before_script:
- zsh --version
script:
- make
